### ISSUE TITLE
AR2 energy ball AS script error

### ISSUE THREAD

**Issue by NoobLCH** [Outerbeast/SC-Half-Life-2-Weapons#2]
Issue happend: energy ball hit something:

Angelscript: Not allowed: in section 'd:/steamlibrary/steamapps/common/sven co-op/svencoop_addon/scripts/maps/hl2/weapon_hl2_ar2.as', at (490, 11):Angelscript:  Function Angelscript: HL2_WEAPONS::ApplyTargetMagnetism:
Angelscript: Message: Index out of bounds
ERROR: Angelscript: CASBaseCallable::Call: Execution of function 'HL2_WEAPONS::ApplyTargetMagnetism' failed!
ERROR: Angelscript: CScheduler::Think: execution of function HL2_WEAPONS::ApplyTargetMagnetism failed!

       array<CBaseEntity@> P_TARGETS( 8 );

       if( g_EntityFuncs.MonstersInSphere( @P_TARGETS, self.pev.origin, 128 ) < 1 )
            return;

        do( P_TARGETS.removeAt( P_TARGETS.findByRef( null ) ) );   <-- Crash here
        while( P_TARGETS.findByRef( null ) >= 0 );

**Comment by Outerbeast** [comment]
This is fixed on my end, but the revision will not be done up until [the other issue](https://github.com/Outerbeast/SC-Half-Life-2-Weapons/issues/1) is resolved.
